"""Public contracts shared by Counterparty Workspace services.

The package is data only: it opens no network, database or file handle, at
import time or later. Three product rules are encoded in the types themselves,
so a caller cannot lose them by accident:

* absence of data never proves absence of risk, so ``missing``,
  ``present_empty``, ``invalid`` and ``restricted`` stay distinct from a real
  zero (:class:`FactValue`);
* an external assessment such as ``zskRiskLevel`` travels as its raw token, and
  an unknown token neither breaks parsing nor becomes a favourable default;
* a reported fact carries at least one resolvable :class:`EvidenceRef`.

Money is a :class:`decimal.Decimal` transported as a plain string, and a source
``$date`` stays an exact instant rather than a calendar day.
"""

from .base import ContractModel, NonEmptyString, SchemaVersion, UtcDatetime
from .enums import (
    ArbitrationAggregation,
    ArtifactFreshness,
    Availability,
    CompanyAddOutcome,
    ComparisonCriterion,
    ComparisonRowStatus,
    ConfirmationStatus,
    CounterpartyRole,
    DecisionOutcome,
    DisplayLevel,
    ErrorCode,
    EvidenceKind,
    PartyRole,
    ProjectDeletionState,
    ProjectFactKey,
    ReportSectionName,
    RiskSignalPolarity,
    RunStatus,
    ThreadStatus,
    ValueType,
    WorkflowStatus,
    YearPolicy,
)
from .envelopes import Error, ProjectEnvelope, RunInfo, ThreadEnvelope
from .evidence import (
    DocumentLocator,
    EvidenceRef,
    PdfPageLocator,
    SpreadsheetRangeLocator,
    TextLinesLocator,
    WordBlockLocator,
)
from .facts import FactValue, FactValueScalar
from .identifiers import (
    ArtifactId,
    ClientRequestId,
    CompanyId,
    DecisionId,
    DocumentId,
    EvidenceRefId,
    FragmentId,
    ProjectId,
    ReportId,
    RunId,
    TenantId,
    ThreadId,
    UserId,
)
from .pagination import DEFAULT_PAGE_LIMIT, MAX_PAGE_LIMIT, Page, PageInfo, ResponseMeta
from .projects import (
    MAX_PROJECT_COMPANIES,
    AddCompaniesRequest,
    AddCompaniesResponse,
    AddCompanyItem,
    AddCompanyResult,
    ArtifactPreview,
    CompanySummary,
    CreateDecisionRequest,
    CreateProjectRequest,
    CreateThreadRequest,
    DeleteProjectRequest,
    Project,
    ProjectCompaniesResponse,
    ProjectCompany,
    ProjectDeletionStatus,
    ProjectFact,
    ProjectFactChange,
    ProjectFactsResponse,
    RemoveCompanyRequest,
    ThreadSummary,
    UpdateProjectFactsRequest,
    UpdateProjectRequest,
    UpdateThreadRequest,
    UserDecision,
)
from .reports import (
    FINANCIAL_ADDITIONAL_FACT_KEYS,
    MAX_COMPARISON_COMPANIES,
    MIN_COMPARISON_COMPANIES,
    SECTION_RECORD_KINDS,
    SECTION_SOURCE_KEYS,
    ZSK_CONFIRMED_DISPLAY_LEVELS,
    Activity,
    ArbitrationAggregate,
    BankRiskAssessment,
    CompanyIdentity,
    CompanyOverview,
    CompanyStatusView,
    Comparison,
    ComparisonRow,
    FinancialPeriod,
    Inspection,
    License,
    Proceeding,
    ProcurementAggregate,
    ProfileRecord,
    ProjectComparison,
    RelatedEntity,
    ReportIdentity,
    ReportRecord,
    ReportSection,
    RiskSignal,
    SectionAvailabilityView,
)
from .values import (
    MAX_FISCAL_YEAR,
    MIN_FISCAL_YEAR,
    CalendarDate,
    CurrencyCode,
    DecimalString,
    FiscalYear,
    Money,
    NonNegativeCount,
    Percent,
    decimal_to_string,
    parse_calendar_date,
    parse_decimal_string,
)

__version__ = "0.1.0"

__all__ = [
    "DEFAULT_PAGE_LIMIT",
    "FINANCIAL_ADDITIONAL_FACT_KEYS",
    "MAX_COMPARISON_COMPANIES",
    "MAX_FISCAL_YEAR",
    "MAX_PAGE_LIMIT",
    "MAX_PROJECT_COMPANIES",
    "MIN_COMPARISON_COMPANIES",
    "MIN_FISCAL_YEAR",
    "SECTION_RECORD_KINDS",
    "SECTION_SOURCE_KEYS",
    "ZSK_CONFIRMED_DISPLAY_LEVELS",
    "Activity",
    "AddCompaniesRequest",
    "AddCompaniesResponse",
    "AddCompanyItem",
    "AddCompanyResult",
    "ArbitrationAggregate",
    "ArbitrationAggregation",
    "ArtifactFreshness",
    "ArtifactId",
    "ArtifactPreview",
    "Availability",
    "BankRiskAssessment",
    "CalendarDate",
    "ClientRequestId",
    "CompanyAddOutcome",
    "CompanyId",
    "CompanyIdentity",
    "CompanyOverview",
    "CompanyStatusView",
    "CompanySummary",
    "Comparison",
    "ComparisonCriterion",
    "ComparisonRow",
    "ComparisonRowStatus",
    "ConfirmationStatus",
    "ContractModel",
    "CounterpartyRole",
    "CreateDecisionRequest",
    "CreateProjectRequest",
    "CreateThreadRequest",
    "CurrencyCode",
    "DecimalString",
    "DecisionId",
    "DecisionOutcome",
    "DeleteProjectRequest",
    "DisplayLevel",
    "DocumentId",
    "DocumentLocator",
    "Error",
    "ErrorCode",
    "EvidenceKind",
    "EvidenceRef",
    "EvidenceRefId",
    "FactValue",
    "FactValueScalar",
    "FinancialPeriod",
    "FiscalYear",
    "FragmentId",
    "Inspection",
    "License",
    "Money",
    "NonEmptyString",
    "NonNegativeCount",
    "Page",
    "PageInfo",
    "PartyRole",
    "PdfPageLocator",
    "Percent",
    "Proceeding",
    "ProcurementAggregate",
    "ProfileRecord",
    "Project",
    "ProjectCompaniesResponse",
    "ProjectCompany",
    "ProjectComparison",
    "ProjectDeletionState",
    "ProjectDeletionStatus",
    "ProjectEnvelope",
    "ProjectFact",
    "ProjectFactChange",
    "ProjectFactKey",
    "ProjectFactsResponse",
    "ProjectId",
    "RelatedEntity",
    "RemoveCompanyRequest",
    "ReportId",
    "ReportIdentity",
    "ReportRecord",
    "ReportSection",
    "ReportSectionName",
    "ResponseMeta",
    "RiskSignal",
    "RiskSignalPolarity",
    "RunId",
    "RunInfo",
    "RunStatus",
    "SchemaVersion",
    "SectionAvailabilityView",
    "SpreadsheetRangeLocator",
    "TenantId",
    "TextLinesLocator",
    "ThreadEnvelope",
    "ThreadId",
    "ThreadStatus",
    "ThreadSummary",
    "UpdateProjectFactsRequest",
    "UpdateProjectRequest",
    "UpdateThreadRequest",
    "UserDecision",
    "UserId",
    "UtcDatetime",
    "ValueType",
    "WordBlockLocator",
    "WorkflowStatus",
    "YearPolicy",
    "__version__",
    "decimal_to_string",
    "parse_calendar_date",
    "parse_decimal_string",
]
