"""Pure domain logic for Counterparty Workspace.

The package holds deterministic computations only: identifier validation,
value parsing with explicit availability semantics, and the evidence ledger
that keeps every factual output resolvable. It opens no network, database or
file handle, including at import time.
"""

from .arbitration import (
    AggregationKind,
    ArbitrationAggregate,
    ArbitrationSummary,
    CaseStatus,
    PartyRole,
    ReportedTotals,
    RoleTotals,
    summarize_arbitration,
)
from .comparison import COMPARISON_RULE_VERSION, build_comparison_rows
from .derivation import DEFAULT_RULE_VERSION, attach_derivation, derived_evidence
from .errors import (
    DomainError,
    DuplicateEvidenceRefError,
    EvidenceError,
    IdentifierError,
    UnavailableValueError,
    UngroundedClaimError,
    UnknownEvidenceRefError,
    UnresolvableEvidenceRefError,
)
from .evidence import (
    EvidenceLedger,
    EvidenceProblem,
    EvidenceResolution,
    ReferenceProblem,
    require_grounded,
)
from .facts import UNKNOWN_AVAILABILITY, Availability, FactSlot, first_available
from .finance import (
    NEGATIVE_EQUITY_NOTE,
    BalanceConsistency,
    CapitalView,
    EquityPosition,
    FinancialHistory,
    FinancialMetric,
    FinancialPeriod,
    FinancialSummary,
    MetricChange,
    PeriodCalculation,
    PeriodCoverage,
    calculate_period,
    compare_metric,
    metric_of,
    summarize_financials,
)
from .identifiers import (
    IdentifierKind,
    IdentifierProblem,
    IdentifierValidation,
    inn_check_digits,
    inn_slot,
    ogrn_slot,
    parse_inn,
    parse_kpp,
    parse_ogrn,
    validate_inn,
    validate_kpp,
    validate_ogrn,
)
from .proceedings import (
    AmountCoverage,
    ExecutionProceeding,
    ProceedingsSummary,
    ProceedingStatus,
    summarize_proceedings,
)
from .values import (
    MAX_FISCAL_YEAR,
    MIN_FISCAL_YEAR,
    MONEY_EXPONENT,
    RATIO_EXPONENT,
    format_decimal,
    is_zero,
    parse_date,
    parse_decimal,
    parse_fiscal_year,
    parse_integer,
    quantize_money,
    ratio,
    subtract_decimals,
    sum_decimals,
)

__version__ = "0.1.0"

__all__ = [
    "COMPARISON_RULE_VERSION",
    "DEFAULT_RULE_VERSION",
    "MAX_FISCAL_YEAR",
    "MIN_FISCAL_YEAR",
    "MONEY_EXPONENT",
    "NEGATIVE_EQUITY_NOTE",
    "RATIO_EXPONENT",
    "UNKNOWN_AVAILABILITY",
    "AggregationKind",
    "AmountCoverage",
    "ArbitrationAggregate",
    "ArbitrationSummary",
    "Availability",
    "BalanceConsistency",
    "CapitalView",
    "CaseStatus",
    "DomainError",
    "DuplicateEvidenceRefError",
    "EquityPosition",
    "EvidenceError",
    "EvidenceLedger",
    "EvidenceProblem",
    "EvidenceResolution",
    "ExecutionProceeding",
    "FactSlot",
    "FinancialHistory",
    "FinancialMetric",
    "FinancialPeriod",
    "FinancialSummary",
    "IdentifierError",
    "IdentifierKind",
    "IdentifierProblem",
    "IdentifierValidation",
    "MetricChange",
    "PartyRole",
    "PeriodCalculation",
    "PeriodCoverage",
    "ProceedingStatus",
    "ProceedingsSummary",
    "ReferenceProblem",
    "ReportedTotals",
    "RoleTotals",
    "UnavailableValueError",
    "UngroundedClaimError",
    "UnknownEvidenceRefError",
    "UnresolvableEvidenceRefError",
    "__version__",
    "attach_derivation",
    "build_comparison_rows",
    "calculate_period",
    "compare_metric",
    "derived_evidence",
    "first_available",
    "format_decimal",
    "inn_check_digits",
    "inn_slot",
    "is_zero",
    "metric_of",
    "ogrn_slot",
    "parse_date",
    "parse_decimal",
    "parse_fiscal_year",
    "parse_inn",
    "parse_integer",
    "parse_kpp",
    "parse_ogrn",
    "quantize_money",
    "ratio",
    "require_grounded",
    "subtract_decimals",
    "sum_decimals",
    "summarize_arbitration",
    "summarize_financials",
    "summarize_proceedings",
    "validate_inn",
    "validate_kpp",
    "validate_ogrn",
]

from .report_reads import (
    ReportReadData,
    build_company_overview,
    report_evidence_id,
    resolve_report_evidence_id,
)
from .report_sections import SECTION_RULE_VERSION, build_report_section

__all__ += [
    "SECTION_RULE_VERSION",
    "ReportReadData",
    "build_company_overview",
    "build_report_section",
    "report_evidence_id",
    "resolve_report_evidence_id",
]
