"""Create the workspace vertical.

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-05

Ownership (``tenants``, ``users``, ``memberships``), the counterparty check
itself (``projects``), the counterparties under review (``project_companies``),
the chats inside the check (``threads``) and the request-id reservations that
make a repeated write harmless (``idempotency_keys``).

Three rules of Specs 02 §4/§6 become database rules here rather than
application conventions:

* a thread and a counterparty reference their project by ``(id, tenant_id)``,
  so nothing can be moved between tenants;
* ``project_companies.slot`` is checked to ``1..20`` and is unique among the
  active rows of a project, so the twenty-first counterparty is refused by
  PostgreSQL;
* ``idempotency_keys`` is keyed by ``(tenant_id, scope, client_request_id)``,
  so a retried request cannot create a second resource.

The cross-schema foreign keys to ``reports`` are ``RESTRICT``: workspace work
never deletes a provided report, and a project can never point at a snapshot
that is gone.

Framework-owned checkpoint tables are not created here. Their DDL belongs to
the library that owns them and is applied by its own deployment step; this
revision neither creates nor claims that namespace.

The revision is fully reversible: ``downgrade`` drops exactly what it created
and leaves the schemas themselves to revision 0001.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
        sa.UniqueConstraint("slug", name="uq_tenants_slug"),
        schema="workspace",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name="uq_users_email"),
        schema="workspace",
    )
    op.create_table(
        "idempotency_keys",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("client_request_id", sa.Uuid(), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "in_flight",
                "completed",
                name="idempotency_state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("resource_kind", sa.Text(), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("response_jsonb", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(state = 'in_flight' AND resource_id IS NULL AND completed_at IS NULL)"
            " OR (state = 'completed' AND resource_id IS NOT NULL"
            " AND completed_at IS NOT NULL)",
            name=op.f("ck_idempotency_keys_completed_names_its_resource"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["workspace.tenants.id"],
            name=op.f("fk_idempotency_keys_tenant_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "scope", "client_request_id", name=op.f("pk_idempotency_keys")
        ),
        schema="workspace",
    )
    op.create_index(
        "ix_idempotency_keys_created_at",
        "idempotency_keys",
        ["created_at"],
        unique=False,
        schema="workspace",
    )
    op.create_table(
        "memberships",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["workspace.tenants.id"],
            name=op.f("fk_memberships_tenant_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["workspace.users.id"],
            name=op.f("fk_memberships_user_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "user_id", name=op.f("pk_memberships")),
        schema="workspace",
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("default_thread_id", sa.Uuid(), nullable=True),
        sa.Column("context_version", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "workflow_status",
            sa.Enum(
                "in_progress",
                "needs_information",
                "decision_recorded",
                name="workflow_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="in_progress",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "context_version >= 0", name=op.f("ck_projects_context_version_non_negative")
        ),
        sa.CheckConstraint(
            "deleted_at IS NULL OR deleted_at >= created_at",
            name=op.f("ck_projects_deleted_after_created"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["workspace.users.id"],
            name=op.f("fk_projects_owner_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["workspace.tenants.id"],
            name=op.f("fk_projects_tenant_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("id", "tenant_id", name="uq_projects_id_tenant_id"),
        schema="workspace",
    )
    op.create_index(
        "ix_projects_owner_id", "projects", ["owner_id"], unique=False, schema="workspace"
    )
    op.create_index(
        "ix_projects_tenant_id_updated_at",
        "projects",
        ["tenant_id", "updated_at"],
        unique=False,
        schema="workspace",
    )
    op.create_table(
        "project_companies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("slot", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "supplier",
                "buyer",
                "contractor",
                "other",
                "unknown",
                name="counterparty_role",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="unknown",
            nullable=False,
        ),
        sa.Column("shortlisted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "added_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("removed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "slot BETWEEN 1 AND 20", name=op.f("ck_project_companies_slot_within_company_limit")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["reports.companies.id"],
            name=op.f("fk_project_companies_company_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "tenant_id"],
            ["workspace.projects.id", "workspace.projects.tenant_id"],
            name="fk_project_companies_project_id_tenant_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.report_snapshots.id"],
            name=op.f("fk_project_companies_report_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_companies")),
        schema="workspace",
    )
    op.create_index(
        "ix_project_companies_company_id",
        "project_companies",
        ["company_id"],
        unique=False,
        schema="workspace",
    )
    op.create_index(
        "ix_project_companies_report_id",
        "project_companies",
        ["report_id"],
        unique=False,
        schema="workspace",
    )
    op.create_index(
        "uq_project_companies_active_company",
        "project_companies",
        ["project_id", "company_id"],
        unique=True,
        schema="workspace",
        postgresql_where=sa.text("removed_at IS NULL"),
    )
    op.create_index(
        "uq_project_companies_active_slot",
        "project_companies",
        ["project_id", "slot"],
        unique=True,
        schema="workspace",
        postgresql_where=sa.text("removed_at IS NULL"),
    )
    op.create_table(
        "threads",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "archived",
                name="thread_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column(
            "last_activity_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'archived') = (archived_at IS NOT NULL)",
            name=op.f("ck_threads_archived_state_matches_timestamp"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "tenant_id"],
            ["workspace.projects.id", "workspace.projects.tenant_id"],
            name="fk_threads_project_id_tenant_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_threads")),
        sa.UniqueConstraint("id", "project_id", name="uq_threads_id_project_id"),
        schema="workspace",
    )
    op.create_index(
        "ix_threads_project_id_last_activity_at",
        "threads",
        ["project_id", "last_activity_at"],
        unique=False,
        schema="workspace",
    )
    op.create_index(
        "ix_threads_tenant_id", "threads", ["tenant_id"], unique=False, schema="workspace"
    )
    # ### end Alembic commands ###
    # The two tables reference each other, so this one is added afterwards:
    # a project points at the chat it opens by default, and losing that chat
    # clears the pointer instead of taking the project with it.
    op.create_foreign_key(
        "fk_projects_default_thread_id",
        "projects",
        "threads",
        ["default_thread_id"],
        ["id"],
        source_schema="workspace",
        referent_schema="workspace",
        ondelete="SET NULL",
    )


def downgrade() -> None:
    """Revert the revision."""
    op.drop_constraint(
        "fk_projects_default_thread_id", "projects", schema="workspace", type_="foreignkey"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_threads_tenant_id", table_name="threads", schema="workspace")
    op.drop_index(
        "ix_threads_project_id_last_activity_at", table_name="threads", schema="workspace"
    )
    op.drop_table("threads", schema="workspace")
    op.drop_index(
        "uq_project_companies_active_slot",
        table_name="project_companies",
        schema="workspace",
        postgresql_where=sa.text("removed_at IS NULL"),
    )
    op.drop_index(
        "uq_project_companies_active_company",
        table_name="project_companies",
        schema="workspace",
        postgresql_where=sa.text("removed_at IS NULL"),
    )
    op.drop_index(
        "ix_project_companies_report_id", table_name="project_companies", schema="workspace"
    )
    op.drop_index(
        "ix_project_companies_company_id", table_name="project_companies", schema="workspace"
    )
    op.drop_table("project_companies", schema="workspace")
    op.drop_index("ix_projects_tenant_id_updated_at", table_name="projects", schema="workspace")
    op.drop_index("ix_projects_owner_id", table_name="projects", schema="workspace")
    op.drop_table("projects", schema="workspace")
    op.drop_table("memberships", schema="workspace")
    op.drop_index(
        "ix_idempotency_keys_created_at", table_name="idempotency_keys", schema="workspace"
    )
    op.drop_table("idempotency_keys", schema="workspace")
    op.drop_table("users", schema="workspace")
    op.drop_table("tenants", schema="workspace")
    # ### end Alembic commands ###
