"""FastAPI composition root for the UI backend.

The process-local collaborators — settings, the session store, the database and
the ownership directory — are built once here and injected through
``app.state``. A test may pass its own; a handler never constructs one, so no
request can end up talking to a store that skipped the checks.

The database is opened by the lifespan, not at import time, and only when the
configuration names one. A process without a database still serves health and
sessions; a project request then refuses with ``dependency_unavailable``
instead of answering as though the workspace were empty.
"""

import uuid
from collections.abc import AsyncIterator
from contextlib import AsyncExitStack, asynccontextmanager

from fastapi import FastAPI, Request
from starlette.middleware.base import RequestResponseEndpoint
from starlette.responses import Response

from .config import Settings
from .database import SessionFactory, open_database
from .errors import install_error_handlers
from .provisioning import ensure_demo_identities
from .routes import (
    auth_router,
    company_directory_router,
    conversation_router,
    decisions_router,
    health_router,
    project_companies_router,
    projects_router,
    report_details_router,
    reports_router,
)
from .sessions import InMemorySessionStore, SessionStore
from .workspace import ProjectDirectory

__all__ = ["app", "create_app", "lifespan"]

REQUEST_ID_HEADER = "x-request-id"


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    """Manage process-local resources owned by the service."""
    settings: Settings = app.state.settings
    async with AsyncExitStack() as resources:
        if app.state.session_factory is None and settings.database_url is not None:
            factory = await resources.enter_async_context(
                open_database(settings.database_url, pool_size=settings.database_pool_size)
            )
            app.state.session_factory = factory
            await ensure_demo_identities(factory, settings)
        app.state.ready = True
        try:
            yield
        finally:
            app.state.ready = False


def create_app(
    *,
    settings: Settings | None = None,
    session_store: SessionStore | None = None,
    project_directory: ProjectDirectory | None = None,
    session_factory: SessionFactory | None = None,
) -> FastAPI:
    """Build the UI API application and register its public routes.

    Args:
        settings: Server-side configuration; read from the environment when
            omitted.
        session_store: Where sessions live; process-local when omitted.
        project_directory: Ownership source for projects and threads; read from
            the workspace schema when omitted.
        session_factory: An already opened database; the lifespan opens one
            from the settings when omitted.

    Returns:
        The configured application.
    """
    application = FastAPI(
        title="Counterparty UI API",
        version="0.1.0",
        lifespan=lifespan,
    )
    application.state.settings = settings if settings is not None else Settings.from_env()
    application.state.session_store = (
        session_store if session_store is not None else InMemorySessionStore()
    )
    application.state.project_directory = project_directory
    application.state.session_factory = session_factory

    @application.middleware("http")
    async def assign_request_id(request: Request, call_next: RequestResponseEndpoint) -> Response:
        """Give every request a correlation id the client can quote back.

        The id is generated by the server rather than taken from a header, so a
        caller cannot make two unrelated requests share one trace.
        """
        request_id = uuid.uuid4().hex
        request.state.request_id = request_id
        response = await call_next(request)
        response.headers[REQUEST_ID_HEADER] = request_id
        return response

    install_error_handlers(application)
    application.include_router(health_router)
    application.include_router(auth_router)
    application.include_router(projects_router)
    application.include_router(company_directory_router)
    application.include_router(project_companies_router)
    application.include_router(reports_router)
    application.include_router(report_details_router)
    application.include_router(decisions_router)
    application.include_router(conversation_router)
    return application


app = create_app()
