"""FastAPI composition root for the UI backend.

The process-local collaborators — settings, the session store and the ownership
directory — are built once here and injected through ``app.state``. A test may
pass its own; a handler never constructs one, so no request can end up talking
to a store that skipped the checks.
"""

import uuid
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager

from fastapi import FastAPI, Request
from starlette.middleware.base import RequestResponseEndpoint
from starlette.responses import Response

from .auth import router as auth_router
from .config import Settings
from .errors import install_error_handlers
from .health import router as health_router
from .sessions import InMemorySessionStore, SessionStore
from .workspace import InMemoryProjectDirectory, ProjectDirectory

__all__ = ["app", "create_app", "lifespan"]

REQUEST_ID_HEADER = "x-request-id"


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    """Manage process-local resources owned by the service."""
    app.state.ready = True
    try:
        yield
    finally:
        app.state.ready = False


def create_app(
    *,
    settings: Settings | None = None,
    session_store: SessionStore | None = None,
    project_directory: ProjectDirectory | None = None,
) -> FastAPI:
    """Build the UI API application and register its public routes.

    Args:
        settings: Server-side configuration; read from the environment when
            omitted.
        session_store: Where sessions live; process-local when omitted.
        project_directory: Ownership source for projects and threads;
            process-local when omitted.

    Returns:
        The configured application.
    """
    application = FastAPI(
        title="Counterparty UI API",
        version="0.1.0",
        lifespan=lifespan,
    )
    application.state.settings = settings if settings is not None else Settings.from_env()
    application.state.session_store = (
        session_store if session_store is not None else InMemorySessionStore()
    )
    application.state.project_directory = (
        project_directory if project_directory is not None else InMemoryProjectDirectory()
    )

    @application.middleware("http")
    async def assign_request_id(request: Request, call_next: RequestResponseEndpoint) -> Response:
        """Give every request a correlation id the client can quote back.

        The id is generated by the server rather than taken from a header, so a
        caller cannot make two unrelated requests share one trace.
        """
        request_id = uuid.uuid4().hex
        request.state.request_id = request_id
        response = await call_next(request)
        response.headers[REQUEST_ID_HEADER] = request_id
        return response

    install_error_handlers(application)
    application.include_router(health_router)
    application.include_router(auth_router)
    return application


app = create_app()
