/**
 * V01: the four transport cases, decoded from bytes the Python encoder wrote.
 *
 * The fixtures under `__fixtures__` are regenerated by
 * `services/agent/scripts/generate_transport_fixtures.py`, so a codec change on
 * either side fails here instead of in the browser.
 */

import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { AgentChat } from './AgentChat';
import answerSse from './__fixtures__/answer.sse?raw';
import cancelledSse from './__fixtures__/cancelled.sse?raw';
import errorSse from './__fixtures__/error.sse?raw';

const PROJECT_ID = '00000000-0000-4000-8000-000000000001';
const THREAD_ID = '00000000-0000-4000-8000-000000000002';

type Recorded = { url: string; body: Record<string, unknown> };

function sseResponse(body: string, { hold = false } = {}, signal?: AbortSignal | null) {
  const encoder = new TextEncoder();
  const stream = new ReadableStream<Uint8Array>({
    start(controller) {
      // One chunk per SSE frame, so the runtime decodes incrementally.
      for (const frame of body.split('\n\n')) {
        if (frame.trim() !== '') controller.enqueue(encoder.encode(`${frame}\n\n`));
      }
      if (!hold) {
        controller.close();
        return;
      }
      // A held stream must fail on abort the way a real response body does.
      signal?.addEventListener('abort', () =>
        controller.error(new DOMException('aborted', 'AbortError')),
      );
    },
  });
  return new Response(stream, {
    status: 200,
    headers: { 'content-type': 'text/event-stream' },
  });
}

function installFetch(chatBody: string, options: { hold?: boolean } = {}) {
  const requests: Recorded[] = [];
  vi.stubGlobal('fetch', async (url: RequestInfo | URL, init: RequestInit = {}) => {
    const recorded: Recorded = {
      url: String(url),
      body: init.body ? JSON.parse(String(init.body)) : {},
    };
    requests.push(recorded);
    if (recorded.url.endsWith('/cancel')) return new Response('{}', { status: 200 });
    return sseResponse(chatBody, options, init.signal);
  });
  return { requests };
}

async function send(text: string) {
  const user = userEvent.setup();
  render(<AgentChat projectId={PROJECT_ID} threadId={THREAD_ID} apiBase="http://agent.test" />);
  await user.type(screen.getByLabelText('Сообщение помощнику'), text);
  await user.click(screen.getByRole('button', { name: 'Отправить' }));
  return user;
}

beforeEach(() => {
  vi.stubGlobal('crypto', { ...globalThis.crypto, randomUUID: () => THREAD_ID });
});

afterEach(() => {
  vi.unstubAllGlobals();
});

describe('V01 assistant-stream ↔ assistant-ui transport', () => {
  it('sends the domain command shape the Agent Service expects', async () => {
    const { requests } = installFetch(answerSse);
    await send('Можно ли перечислять 80% аванса?');

    await waitFor(() => expect(requests).toHaveLength(1));
    expect(requests[0]!.url).toBe('http://agent.test/rpc/agent/chat');
    expect(requests[0]!.body).toMatchObject({
      project_id: PROJECT_ID,
      thread_id: THREAD_ID,
      stream: true,
      commands: [
        {
          type: 'add-message',
          message: { text: 'Можно ли перечислять 80% аванса?', document_ids: [] },
        },
      ],
    });
  });

  it('renders streamed assistant text', async () => {
    installFetch(answerSse);
    await send('Можно ли перечислять 80% аванса?');

    await waitFor(() =>
      expect(
        screen.getByText(/Аванс 80% от 2,4 млн ₽ — это 1,92 млн ₽ до отгрузки/),
      ).toBeVisible(),
    );
    await waitFor(() => expect(screen.getByTestId('run-status')).toHaveTextContent('completed'));
    expect(screen.getByText('Можно ли перечислять 80% аванса?')).toBeVisible();
  });

  it('renders the typed activity of a run that did not finish cleanly', async () => {
    // A clean completion drops the single-step trail (the answer stands alone);
    // a cancelled run keeps it, so the typed activity is still inspectable.
    installFetch(cancelledSse);
    await send('/slow проверь отчёт');

    const activity = await screen.findByText('Читаю условия поставки');
    expect(activity).toHaveAttribute('data-kind', 'reading_document');
    await waitFor(() => expect(activity).toHaveAttribute('data-status', 'failed'));
  });

  it('keeps the trail of actions under a clean answer, collapsed', async () => {
    const user = userEvent.setup();
    installFetch(answerSse);
    await send('Проверь условия');

    await screen.findByText(/Аванс 80%/);
    // The record of what the assistant looked at stays above the answer,
    // collapsed behind «Что было сделано».
    const toggle = screen.getByRole('button', { name: /Что было сделано/ });
    expect(screen.getByText('Читаю условия поставки')).not.toBeVisible();
    await user.click(toggle);
    expect(screen.getByText('Читаю условия поставки')).toBeVisible();
  });

  it('surfaces a terminal error without losing the run status', async () => {
    installFetch(errorSse);
    await send('/fail проверь отчёт');

    const alert = await screen.findByRole('alert');
    expect(alert).toHaveTextContent('Источник сведений недоступен. Попробуйте позже.');
    await waitFor(() => expect(screen.getByTestId('run-status')).toHaveTextContent('failed'));
  });

  it('keeps partial output and the cancelled status for a cancelled run', async () => {
    installFetch(cancelledSse);
    await send('/slow проверь отчёт');

    await waitFor(() => expect(screen.getByTestId('run-status')).toHaveTextContent('cancelled'));
    expect(screen.getByText(/Разбираю документ/)).toBeVisible();
  });

  it('stops an in-flight run with the separate cancel command', async () => {
    // Keep only the frames that arrive before the run settles, then hold open.
    const inFlight = answerSse.split('\n\n').slice(0, 2).join('\n\n');
    const { requests } = installFetch(inFlight, { hold: true });
    const user = await send('Можно ли перечислять 80% аванса?');

    await waitFor(() => expect(screen.getByTestId('run-status')).toHaveTextContent('running'));
    await user.click(await screen.findByRole('button', { name: 'Остановить' }));

    await waitFor(() =>
      expect(requests.map((request) => request.url)).toContain(
        'http://agent.test/rpc/agent/runs/00000000-0000-4000-8000-000000000004/cancel',
      ),
    );
    await waitFor(() => expect(screen.getByTestId('run-status')).toHaveTextContent('cancelled'));
  });
});
