/** Recheck only mobile draft touch targets and favicon after the reviewed I4 fix. */
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { ApiProject } from '../src/api/contracts.ts';
import { startChrome } from './browser.ts';

const original = JSON.parse(await readFile('../../artifacts/qa/WEB-08/manifest.json', 'utf8')) as { sourceSHA: string; projects: { id: string; viewport: string }[] };
const projectId = original.projects.find((item) => item.viewport === 'mobile')!.id;
const baseURL = process.env.WEB08_URL ?? 'http://127.0.0.1:5173';
const output = resolve('../../artifacts/qa/WEB-08/follow-up');
const sourceSHA = execFileSync('git', ['rev-parse', 'HEAD'], { encoding: 'utf8' }).trim();
const dirty = execFileSync('git', ['status', '--porcelain', '--', '../..', ':!../../artifacts/qa/WEB-08'], { encoding: 'utf8' }).trim();
if (dirty) throw new Error('Commit source before targeted verification');
await mkdir(output, { recursive: true });
const chrome = await startChrome(process.env.WEB08_CHROME ?? '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome');
const result = { sourceSHA, originalSourceSHA: original.sourceSHA, scope: 'Mobile draft targets + favicon only; no full flow repeat', projectId, browser: chrome.browser.version(), consoleErrors: [] as { text: string; url: string }[], pageErrors: [] as string[], targets: [] as { name: string; width: number; height: number; minHeight: string; parentClass: string; className: string; rules: string[] }[], favicon: { path: '', status: 0 }, viewport: { width: 390, height: 844 }, innerWidth: 0, overflow: 0, composerVisible: false, screenshot: 'mobile-draft.png', verdict: 'fail' };
try {
  const context = await chrome.browser.newContext({ viewport: result.viewport, locale: 'ru-RU', isMobile: true, hasTouch: true });
  await context.request.post(`${baseURL}/api/v1/auth/session`, { data: { login: 'demo-analyst' } });
  const project = await (await context.request.get(`${baseURL}/api/v1/projects/${projectId}`)).json() as ApiProject;
  const page = await context.newPage();
  page.setDefaultTimeout(12000);
  page.on('console', (message) => { if (message.type() === 'error') result.consoleErrors.push({ text: message.text(), url: message.location().url }); });
  page.on('pageerror', (error) => result.pageErrors.push(error.message));
  await page.goto(`${baseURL}/checks/${projectId}/chats/${project.default_thread_id}`, { waitUntil: 'networkidle' });
  const composer = page.getByRole('textbox', { name: 'Сообщение помощнику' });
  await composer.fill('Проверить аванс, сохранить основание — mobile');
  const materials = page.getByRole('button', { name: 'Материалы', exact: true });
  await materials.click();
  const panel = page.getByRole('complementary', { name: 'Материалы проверки' });
  await panel.getByRole('button', { name: /ИНН 1684017097/ }).click();
  await panel.getByRole('button', { name: /^Финансы/ }).click();
  await panel.getByRole('button', { name: 'Обсудить: Выручка', exact: true }).first().click();
  await panel.waitFor({ state: 'hidden' });
  await materials.click();
  await panel.getByRole('button', { name: 'К материалам', exact: true }).click();
  await panel.getByRole('button', { name: 'Сравнить компании', exact: true }).click();
  await panel.getByRole('button', { name: 'Сравнить выбранные (2)', exact: true }).click();
  await panel.getByRole('button', { name: 'Обсудить сравнение', exact: true }).click();
  await panel.waitFor({ state: 'hidden' });
  const chips = page.locator('[aria-label="Материалы в черновике"]');
  assert.equal(await chips.locator('button').count(), 3);
  result.targets = await chips.locator('button').evaluateAll((buttons) => buttons.map((button) => { const box = button.getBoundingClientRect(); const rules: string[] = []; const collect = (entries: CSSRuleList) => { for (const entry of entries) { if (entry instanceof CSSStyleRule && entry.style.minHeight && button.matches(entry.selectorText)) rules.push(`${entry.selectorText}: ${entry.style.cssText}`); if ('cssRules' in entry) collect((entry as CSSGroupingRule).cssRules); } }; for (const sheet of document.styleSheets) { try { collect(sheet.cssRules); } catch { /* Foreign stylesheets cannot be inspected. */ } } return { name: button.getAttribute('aria-label') ?? button.textContent ?? '', width: box.width, height: box.height, minHeight: getComputedStyle(button).minHeight, parentClass: button.parentElement?.className ?? '', className: button.className, rules }; }));
  result.innerWidth = await page.evaluate(() => window.innerWidth);
  result.overflow = await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth);
  const box = await composer.boundingBox();
  result.composerVisible = !!box && box.y >= 0 && box.y + box.height <= result.viewport.height;
  assert.equal(result.overflow, 0);
  assert.ok(result.composerVisible);
  result.favicon.path = (await page.locator('link[rel="icon"]').getAttribute('href'))!;
  result.favicon.status = (await context.request.get(`${baseURL}${result.favicon.path}`)).status();
  assert.equal(result.favicon.status, 200);
  assert.ok(result.targets.every((target) => target.width >= 44 && target.height >= 44));
  assert.deepEqual(result.consoleErrors, []);
  assert.deepEqual(result.pageErrors, []);
  await page.evaluate(() => document.fonts.ready);
  await page.screenshot({ path: resolve(output, result.screenshot) });
  result.verdict = 'pass';
} finally {
  await writeFile(resolve(output, 'manifest.json'), `${JSON.stringify(result, null, 2)}\n`);
  await chrome.close();
  console.log(JSON.stringify(result, null, 2));
}
