import { requestJson } from './client';
import type {
  CompanyOverview,
  ComparisonInput,
  ProjectComparison,
  ReportEvidence,
  ReportSection,
  SectionName,
} from './reportContracts';

/** Scope includes the project even for immutable shared snapshots. */
export const reportKeys = {
  project: (projectId: string) => ['workspace', 'projects', projectId, 'reports'] as const,
  overview: (projectId: string, reportId: string) =>
    [...reportKeys.project(projectId), reportId, 'overview'] as const,
  section: (projectId: string, reportId: string, section: SectionName) =>
    [...reportKeys.project(projectId), reportId, 'section', section] as const,
  evidence: (projectId: string, ref: string) =>
    [...reportKeys.project(projectId), 'evidence', ref] as const,
  comparison: (projectId: string, contextVersion: number, selection: ComparisonInput) =>
    [...reportKeys.project(projectId), 'comparison', contextVersion, selection] as const,
};
export async function getOverview(reportId: string): Promise<CompanyOverview> {
  return (await requestJson<CompanyOverview>(`/reports/${encodeURIComponent(reportId)}/overview`))
    .data;
}

export interface ReportSummaryBullet {
  readonly tone: 'risk' | 'ok' | 'neutral';
  readonly text: string;
}
export interface ReportSummary {
  readonly bullets: readonly ReportSummaryBullet[];
}

/** The task-aware "на что обратить внимание" block, generated by the assistant. */
export async function getReportSummary(
  projectId: string,
  reportId: string,
): Promise<ReportSummary> {
  return (
    await requestJson<ReportSummary>(
      `/projects/${encodeURIComponent(projectId)}/reports/${encodeURIComponent(reportId)}/summary`,
    )
  ).data;
}
export async function getSection(
  reportId: string,
  section: SectionName,
  cursor: string | null,
): Promise<ReportSection> {
  const query = new URLSearchParams({ limit: '20' });
  if (cursor) query.set('cursor', cursor);
  return (
    await requestJson<ReportSection>(
      `/reports/${encodeURIComponent(reportId)}/sections/${section}?${query}`,
    )
  ).data;
}
export async function getEvidence(projectId: string, evidenceRef: string): Promise<ReportEvidence> {
  return (
    await requestJson<ReportEvidence>(
      `/projects/${encodeURIComponent(projectId)}/evidence/${encodeURIComponent(evidenceRef)}`,
    )
  ).data;
}
export async function compareReports(
  projectId: string,
  input: ComparisonInput,
): Promise<ProjectComparison> {
  return (
    await requestJson<ProjectComparison>(`/projects/${encodeURIComponent(projectId)}/comparisons`, {
      method: 'POST',
      body: JSON.stringify(input),
    })
  ).data;
}
